apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: pi
spec:
  schedule: "*/1 * * * *"       
  concurrencyPolicy: "Replace"  
  startingDeadlineSeconds: 200  
  suspend: false                
  successfulJobsHistoryLimit: 3 
  failedJobsHistoryLimit: 1     
  jobTemplate:                  
    spec:
      template:
        metadata:
          labels:               
            parent: "cronjobpi"
        spec:
          containers:
          - name: pi
            image: rhel7
            command: ["curl",  "--location", "--request POST", "http://pam-poc-service-pam-poc.apps-crc.testing/rest/server/containers/pam-poc-kjar-1.0-SNAPSHOT/processes/pam-poc-kjar.MyProcess/instances", "--header 'Authorization: Basic a2llc2VydmVyOmtpZXNlcnZlcjEh'","--header 'Content-Type: application/json' ","--header 'Cookie: 689c3a6aea7448f84a0b4e277a2a7d49=7040f8880aadf5c9a4a361035ff4de23; JSESSIONID=A304899FE0017ED39904610D055A47EB'","--data-raw '{"customerName":"Paulo"}'"]
          restartPolicy: OnFailure